### ISSUE TITLE
lib/** files are not being watched 

### ISSUE THREAD

**Issue by eckdanny-osi** [ca-cwds/case-management#126]
kind of annoying to constantly be restarting rails server... can these be watched and reloaded as app/** files?

**Comment by edgibbs** [comment]
So they should be autoloaded unless you're running in a production environment, which you may be due to a docker setup.  It looks like we can try:

`config.eager_load_paths << Rails.root.join('lib')`

over  the current:

`config.autoload_paths << Rails.root.join('lib')`

if you want to see if that helps.

**Comment by eckdanny-osi** [comment]
I noticed this only occurs when running the docker-ized dev environment. When running the rails server locally, a browser refresh reflects updates.

**Comment by eckdanny-osi** [comment]
closing in favor of #134
